const data = {
    products: [
        {
            _id: '1',
            name: "jaggary product",
            category: 'sweet Product',
            image: '/image/gul1.jpg',
            price: 80,
            brand: 'Natural',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: "suger product",
            category: 'sweet Product',
            image: '/image/sugar11.jpg',
            price: 36,
            brand: 'lok mangal',
            rating: 3.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: "Groundnut product",
            category: 'Regular Product',
            image: '/image/groundnut.jpg',
            price: 110,
            brand: 'Natural',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: "Maida product",
            category: 'sweet Product',
            image: '/image/maida.jpg',
            price: 36,
            brand: 'Natural',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: "ToorDal product",
            category: 'Pulses',
            image: '/image/toordal1.jpg',
            price: 80,
            brand: 'Golden Bird',
            rating: 4.5,
            numReviews: 13,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: "Sooji product",
            category: 'Regular Product',
            image: '/image/suji1.jpg',
            price: 26,
            brand: 'Premium',
            rating: 4.5,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '7',
            name: "Soyabean oil product",
            category: 'oil Product',
            image: '/image/soyaoil.jpg',
            price: 140,
            brand: 'Fortune',
            rating: 4.5,
            numReviews: 18,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: "Besan product",
            category: 'Regular Product',
            image: '/image/besan2.jpg',
            price: 65,
            brand: 'G Pure',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '9',
            name: "Poha product",
            category: 'Regular Product',
            image: '/image/poha.jpg',
            price: 35,
            brand: 'Natural',
            rating: 4.5,
            numReviews: 16,
            description: 'high quality product',
        },
        {
            _id: '10',
            name: " Vanaspati Ghee product",
            category: 'oil Product',
            image: '/image/ghee1.jpg',
            price: 75,
            brand: 'Natural',
            rating: 4.5,
            numReviews: 16,
            description: 'high quality product',
        },

    ],

};

export default data;
